url: http://localhost:3000
port: 3000
db:
  host: 35.244.49.159
  port: 5432
  db: jokerman
  user: vitpilen
  pass: husqvarna
redis:
  host: localhost
  port: 6379
id: aid
proxyBypassHosts:
  - api.deepl.com
  - api-free.deepl.com
  - www.recaptcha.net
  - hcaptcha.com
  - challenges.cloudflare.com
strictPublicVisibility: true
signToActivityPubGet: true
